blank_issues_enabled: false

contact_links:
  - name: 'ğŸ™â€€Ask for help'
    url: https://github.com/duncanmcclean/simple-commerce/discussions/new
    about: 'Start a discussion to ask for help!'
  - name: 'ğŸ’¡â€€Feature Requests'
    url: https://github.com/duncanmcclean/simple-commerce/discussions/new
    about: 'Start a discussion to submit your feature request.'
  - name: 'Get in touch'
    url: https://duncanmcclean.com/help
    about: "If you'd rather talk privately, send over an email."
